### ISSUE TITLE
activate mailiing list

### ISSUE THREAD

**Issue by MarcinKosinski** [whyRconf/whyRconf.github.io#2]

**Comment by MarcinKosinski** [comment]
php smtp server? phpMailer? https://github.com/PHPMailer/PHPMailer

**Comment by MarcinKosinski** [comment]
https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-postfix-as-a-send-only-smtp-server-on-ubuntu-14-04

**Comment by pbiecek** [comment]
Zapytałbym Marcina Borkowskiego (admin na MINI) o listy mailingowe
pewnie już coś jest zainstalowane i on mógłby to skonfigurować,
instalacja od zera takiego serwera to pózniej problem z utrzymaniem, odrobaczaniem itp

**Comment by MarcinKosinski** [comment]
nieaktualne
