### ISSUE TITLE
Dodać złotego sponsora - UBS

### ISSUE THREAD

**Issue by MarcinKosinski** [whyRconf/whyRconf.github.io#31]
![ubs_semibold_44_68x184_black](https://user-images.githubusercontent.com/6773454/28710048-e42330ca-7382-11e7-9c96-614e30917e8b.png)

@EmilBuszylo czy dodałbyś nową podsekcję w sekcji `Sponsorzy` ze sponsorem `Złotym` i dodał logo UBS?

**Comment by MarcinKosinski** [comment]
[ubs_semibold_44_68x184_rgb.zip](https://github.com/whyRconf/whyRconf.github.io/files/1190245/ubs_semibold_44_68x184_rgb.zip)

@EmilBuszylo poprzednie logo zostalo przeslane w zbyt malej rozdzielczosci i w nieodpowiedniej kolorystyce. Zdarza sie. Czy moglbym prosic o wymiane obecnego logo na to, ktore dorzucam teraz w tej wiadomosci?

Czy odleglosc tego loga od napisu ktory bylby nad logiem i pod logiem, moze wynosic tyle (co najmniej) co literka `B` w napisie? Taka mala prosba od naszego sponsora : )

**Comment by MarcinKosinski** [comment]
@EmilBuszylo jaki jest status sprawy?

**Comment by EmilBuszylo** [comment]
Do ok. godziny 22:00 sprawa powinna zostać załatwiona.
Co do wielkości odstępu, dołoże starań żeby był jak najbardziej zbliżony do literki "B"
