### ISSUE TITLE
logo MI^2 Data Lab

### ISSUE THREAD

**Issue by MarcinKosinski** [whyRconf/whyRconf.github.io#37]
@pbiecek na stronie jest jeszcze stare czarno białe logo MI2.
Czy wolałbyś aby ostatecznie zostało podmieniona na nowe fioletowe? To logo pojawi się też na okładce książki konferencyjnej oraz na plakatach.

Tutaj dodajemy logo MI2 do strony https://github.com/whyRconf/whyRconf.github.io/blob/master/index.html#L690

**Comment by pbiecek** [comment]
Dzięki, fioletowe wygląda lepiej,
podmieniłem na www na 
https://github.com/whyRconf/hackathon/blob/master/img/29011682.jpeg

**Comment by pbiecek** [comment]
fixed in 99ee5475fc2541cc4369014dd5af00e08f23a0aa
